
# Shared definition block
shared:
  image: openjdk
  
  # Job definition block
jobs:
  main:
    requires: [~pr, ~commit]
    # Steps definition block.
    steps:
      - whereisi: java -version
      - export: export GREETING="Hello, world!"
      - hello: echo $GREETING
      - set-metadata: meta set example.coverage 99.95
#  second_job:
#    requires: [main] # second_job will run after main job is done
#    steps:
#      - make_target: make greetings
#      - get-metadata: meta get example
